const locationData = {
  nigeria: {
    abia: ["Umuahia", "Aba", "Arochukwu"],
    adamawa: ["Yola", "Jimeta", "Mubi", "Numan"],
    akwa_ibom: ["Uyo", "Ikot Ekpene", "Ikot Abasi", "Oron"],
    anambra: ["Awka", "Onitsha", "Nnewi"],
    bauchi: ["Bauchi", "Azare", "Jama'are", "Misau", "Katagum"],
    bayelsa: ["Yenagoa", "Brass"],
    benue: ["Makurdi", "Gboko", "Otukpo"],
    borno: ["Maiduguri", "Biu", "Dikwa", "Bama", "Kukawa"],
    cross_river: ["Calabar", "Ogoja", "Ugep"],
    delta: ["Asaba", "Warri", "Sapele", "Burutu", "Ughelli"],
    ebonyi: ["Abakaliki"],
    edo: ["Benin City", "Uromi"],
    ekiti: ["Ado Ekiti", "Ikere-Ekiti", "Ijero", "Ise Ekiti", "Ilawe Ekiti"],
    enugu: ["Enugu", "Nsukka"],
    fct: ["Abuja"],
    gombe: ["Gombe", "Kumo"],
    imo: ["Owerri", "Orlu", "Okigwe"],
    jigawa: ["Dutse", "Birnin Kudu", "Hadejia", "Gumel"],
    kaduna: ["Kaduna", "Zaria"],
    kano: ["Kano"],
    katsina: ["Katsina", "Funtua"],
    kebbi: ["Birnin Kebbi", "Argungu", "Yelwa"],
    kogi: ["Lokoja", "Okene", "Kabba"],
    kwara: ["Ilorin", "Offa"],
    lagos: ["Lagos", "Ikeja", "Ikorodu", "Epe", "Badagry", "Mushin", "Shomolu"],
    nasarawa: ["Lafia"],
    niger: ["Minna", "Bida", "Kontagora", "Suleja"],
    ogun: ["Abeokuta", "Ijebu-Ode", "Sagamu"],
    ondo: ["Akure", "Ondo", "Owo", "Ikare"],
    osun: ["Oshogbo", "Ile-Ife", "Ilesa", "Ede", "Iwo", "Ila"],
    oyo: ["Ibadan", "Ogbomosho", "Oyo", "Iseyin", "Shaki", "Igboho", "Kisi"],
    plateau: ["Jos", "Bukuru", "Pankshin"],
    rivers: ["Port Harcourt", "Bonny", "Degema", "Buguma"],
    sokoto: ["Sokoto"],
    taraba: ["Jalingo", "Ibi", "Muri"],
    yobe: ["Damaturu", "Gashua", "Potiskum"],
    zamfara: ["Gusau", "Kaura Namoda"],
  },
};
